export const tempoTokens = {
  color: {
    backgroundLight: '#F4F4F0',
    backgroundDark: '#0C0C0E',
    cardLight: '#FFFFFF',
    cardDark: '#141416',
    primary: '#C9A86C',
    primaryLight: '#A16207',
    cyan: '#A8A29E',
    cyanLight: '#78716C',
    textMuted: '#6B6B70',
    textMutedDark: '#71717A',
    danger: '#E5484D',
    borderLight: '#D4D4D8',
    borderDark: '#2E2E32',
    glow: 'rgba(201, 168, 108, 0.22)',
    phosphor: '#C9A86C',
    phosphorLight: '#A16207',
  },
  radius: {
    card: 6,
    cardLight: 8,
    button: 4,
    buttonLight: 6,
    tile: 6,
    bar: 3,
  },
  space: {
    screen: 20,
    section: 16,
    item: 8,
    cardPadding: 16,
    listRow: 12,
    listIndent: 14,
    listSection: 14,
    statRow: 6,
  },
  size: {
    button: 44,
    buttonSm: 36,
    iconButton: 44,
    chartHeight: 48,
    barHeight: 6,
    activityListMaxHeight: 280,
  },
  font: {
    mono: 'JetBrainsMono_400Regular',
    monoSemiBold: 'JetBrainsMono_600SemiBold',
    sans: 'Inter_400Regular',
    sansSemiBold: 'Inter_600SemiBold',
  },
  meter: {
    segments: 20,
    verticalSegments: 12,
    height: 10,
    gap: 2,
    staggerMs: 30,
    rowStaggerMs: 40,
  },
  chart: {
    barHeight: 6,
    barTrackHeight: 8,
    columnMaxHeight: 72,
    radius: 3,
    staggerMs: 40,
    durationMs: 350,
  },
} as const;
