import {
  Activity,
  AlarmClock,
  Apple,
  Bed,
  Bike,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Calculator,
  Camera,
  Car,
  Circle,
  Cloud,
  Code,
  Coffee,
  Dice5,
  Dog,
  Droplets,
  Dumbbell,
  FileText,
  Film,
  Flag,
  Flame,
  Footprints,
  Gamepad2,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Key,
  Keyboard,
  Languages,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  MapPin,
  MessageSquare,
  Mic,
  Microscope,
  Monitor,
  Moon,
  Music,
  Paintbrush,
  Palette,
  PenTool,
  Pencil,
  Phone,
  Pill,
  Plane,
  Puzzle,
  Rocket,
  ShoppingCart,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Sunrise,
  Target,
  Timer,
  Train,
  TreePine,
  Tv,
  Users,
  Utensils,
  Wallet,
  Waves,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';

const ICON_MAP: Record<string, LucideIcon> = {
  code: Code,
  target: Target,
  laptop: Laptop,
  pencil: Pencil,
  brain: Brain,
  zap: Zap,
  timer: Timer,
  coffee: Coffee,
  monitor: Monitor,
  keyboard: Keyboard,
  'file-text': FileText,
  'message-square': MessageSquare,
  'book-open': BookOpen,
  book: Book,
  'graduation-cap': GraduationCap,
  languages: Languages,
  microscope: Microscope,
  lightbulb: Lightbulb,
  calculator: Calculator,
  library: Library,
  'pen-tool': PenTool,
  dumbbell: Dumbbell,
  footprints: Footprints,
  heart: Heart,
  bike: Bike,
  activity: Activity,
  pill: Pill,
  bed: Bed,
  apple: Apple,
  droplets: Droplets,
  stethoscope: Stethoscope,
  utensils: Utensils,
  sparkles: Sparkles,
  home: Home,
  car: Car,
  'shopping-cart': ShoppingCart,
  briefcase: Briefcase,
  wallet: Wallet,
  phone: Phone,
  plane: Plane,
  train: Train,
  key: Key,
  dog: Dog,
  music: Music,
  'gamepad-2': Gamepad2,
  users: Users,
  camera: Camera,
  tv: Tv,
  palette: Palette,
  film: Film,
  headphones: Headphones,
  'dice-5': Dice5,
  paintbrush: Paintbrush,
  mic: Mic,
  moon: Moon,
  sun: Sun,
  cloud: Cloud,
  'tree-pine': TreePine,
  waves: Waves,
  sofa: Sofa,
  'alarm-clock': AlarmClock,
  sunrise: Sunrise,
  circle: Circle,
  star: Star,
  flag: Flag,
  'map-pin': MapPin,
  gift: Gift,
  wrench: Wrench,
  puzzle: Puzzle,
  rocket: Rocket,
  flame: Flame,
  leaf: Leaf,
};

export const ICON_CATEGORIES = [
  {
    label: 'Focus & Work',
    icons: [
      'code',
      'target',
      'laptop',
      'pencil',
      'brain',
      'zap',
      'timer',
      'coffee',
      'monitor',
      'keyboard',
      'file-text',
      'message-square',
    ],
  },
  {
    label: 'Learning',
    icons: [
      'book-open',
      'book',
      'graduation-cap',
      'languages',
      'microscope',
      'lightbulb',
      'calculator',
      'library',
      'pen-tool',
    ],
  },
  {
    label: 'Health',
    icons: [
      'dumbbell',
      'footprints',
      'heart',
      'bike',
      'activity',
      'pill',
      'bed',
      'apple',
      'droplets',
      'stethoscope',
    ],
  },
  {
    label: 'Life',
    icons: [
      'utensils',
      'sparkles',
      'home',
      'car',
      'shopping-cart',
      'briefcase',
      'wallet',
      'phone',
      'plane',
      'train',
      'key',
      'dog',
    ],
  },
  {
    label: 'Leisure',
    icons: [
      'music',
      'gamepad-2',
      'users',
      'camera',
      'tv',
      'palette',
      'film',
      'headphones',
      'dice-5',
      'paintbrush',
      'mic',
    ],
  },
  {
    label: 'Rest',
    icons: ['moon', 'sun', 'cloud', 'tree-pine', 'waves', 'sofa', 'alarm-clock', 'sunrise'],
  },
  {
    label: 'Other',
    icons: [
      'circle',
      'star',
      'flag',
      'map-pin',
      'gift',
      'wrench',
      'puzzle',
      'rocket',
      'flame',
      'leaf',
    ],
  },
] as const;

export function getActivityIcon(name?: string): LucideIcon {
  if (!name) return Circle;
  return ICON_MAP[name] ?? Circle;
}

export function formatIconName(name: string): string {
  return name.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export const ICON_OPTIONS = Object.keys(ICON_MAP);
