import {
  Activity,
  Bed,
  Bike,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Camera,
  Car,
  Circle,
  Cloud,
  Code,
  Coffee,
  Dumbbell,
  Film,
  Flag,
  Footprints,
  Gamepad2,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Languages,
  Laptop,
  Lightbulb,
  MapPin,
  Microscope,
  Moon,
  Music,
  Palette,
  Pencil,
  Phone,
  Pill,
  ShoppingCart,
  Sparkles,
  Star,
  Sun,
  Target,
  Timer,
  TreePine,
  Tv,
  Users,
  Utensils,
  Wallet,
  Waves,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';

const ICON_MAP: Record<string, LucideIcon> = {
  code: Code,
  target: Target,
  laptop: Laptop,
  pencil: Pencil,
  brain: Brain,
  zap: Zap,
  timer: Timer,
  coffee: Coffee,
  'book-open': BookOpen,
  book: Book,
  'graduation-cap': GraduationCap,
  languages: Languages,
  microscope: Microscope,
  lightbulb: Lightbulb,
  dumbbell: Dumbbell,
  footprints: Footprints,
  heart: Heart,
  bike: Bike,
  activity: Activity,
  pill: Pill,
  bed: Bed,
  utensils: Utensils,
  sparkles: Sparkles,
  home: Home,
  car: Car,
  'shopping-cart': ShoppingCart,
  briefcase: Briefcase,
  wallet: Wallet,
  phone: Phone,
  music: Music,
  'gamepad-2': Gamepad2,
  users: Users,
  camera: Camera,
  tv: Tv,
  palette: Palette,
  film: Film,
  headphones: Headphones,
  moon: Moon,
  sun: Sun,
  cloud: Cloud,
  'tree-pine': TreePine,
  waves: Waves,
  circle: Circle,
  star: Star,
  flag: Flag,
  'map-pin': MapPin,
  gift: Gift,
  wrench: Wrench,
};

export const ICON_CATEGORIES = [
  {
    label: 'Focus & Work',
    icons: ['code', 'target', 'laptop', 'pencil', 'brain', 'zap', 'timer', 'coffee'],
  },
  {
    label: 'Learning',
    icons: ['book-open', 'book', 'graduation-cap', 'languages', 'microscope', 'lightbulb'],
  },
  {
    label: 'Health',
    icons: ['dumbbell', 'footprints', 'heart', 'bike', 'activity', 'pill', 'bed'],
  },
  {
    label: 'Life',
    icons: ['utensils', 'sparkles', 'home', 'car', 'shopping-cart', 'briefcase', 'wallet', 'phone'],
  },
  {
    label: 'Leisure',
    icons: ['music', 'gamepad-2', 'users', 'camera', 'tv', 'palette', 'film', 'headphones'],
  },
  {
    label: 'Rest',
    icons: ['moon', 'sun', 'cloud', 'tree-pine', 'waves'],
  },
  {
    label: 'Other',
    icons: ['circle', 'star', 'flag', 'map-pin', 'gift', 'wrench'],
  },
] as const;

export function getActivityIcon(name?: string): LucideIcon {
  if (!name) return Circle;
  return ICON_MAP[name] ?? Circle;
}

export function formatIconName(name: string): string {
  return name.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export const ICON_OPTIONS = Object.keys(ICON_MAP);
